apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: jrnl
build:
  artifacts:
  - image: frontend
    context: frontend
deploy:
  kubectl:
    manifests:
    - kubernetes/namespace.yaml
    - frontend/kubernetes/deployment.yaml
